insert into Publishers values('Rockstar Games')
insert into Publishers values('Electronic Arts')
insert into Publishers values('Tencent Games')
insert into Publishers values('Sony Interactive Entertainment')
insert into Publishers values('Microsoft')
insert into Publishers values('Activision Blizzard')
insert into Publishers values('Nintendo')
insert into Publishers values('Bandai Namco')
insert into Publishers values('Take-Two Interactive')
insert into Publishers values('Ubisoft')
insert into Publishers values('Square Enix')
insert into Publishers values('Konami Games')
insert into Publishers values('Sega')
insert into Publishers values('Capcom')
insert into Publishers values('2K Games')
insert into Publishers values('Bethesda Softworks')
insert into Publishers values('505 Games')
insert into Publishers values('Naughty Dog')

insert into Platforms values('PlayStation 2','PS2')
insert into Platforms values('PlayStation 3','PS3')
insert into Platforms values('PlayStation 4','PS4')
insert into Platforms values('PlayStation 5','PS5')
insert into Platforms values('Microsoft Windows','PC')
insert into Platforms([Platform]) values('Nintendo Switch')
insert into Platforms([Platform]) values('Xbox')
insert into Platforms([Platform]) values('Xbox 360')
insert into Platforms([Platform]) values('Xbox One')
insert into Platforms([Platform]) values('Xbox One S')
insert into Platforms([Platform]) values('Xbox One X')
insert into Platforms([Platform]) values('Xbox Series S')
insert into Platforms([Platform]) values('Xbox Series X')

insert into Genres values('Action')
insert into Genres values('Adventure')
insert into Genres values('Role-Playing')
insert into Genres values('Fighting')
insert into Genres values('Puzzle')
insert into Genres values('Sports')
insert into Genres values('Racing')
insert into Genres values('Simulation')
insert into Genres values('Casual')
insert into Genres values('Strategy')
insert into Genres values('Survival')
insert into Genres values('Battle Royale')
insert into Genres values('Horror')
insert into Genres values('Sci-Fi')
insert into Genres values('Shooting')
insert into Genres values('Open-World')
insert into Genres values('Singleplayer')
insert into Genres values('Multiplayer')

insert into Regions values('America')
insert into Regions values('Europe')
insert into Regions values('Asia')
insert into Regions values('Japan')

insert into PaymentMethods values('Card')
insert into PaymentMethods values('PayPal')
insert into PaymentMethods values('Amazon Pay')
insert into PaymentMethods values('Apple Pay')
insert into PaymentMethods values('Google Pay')

insert into Games(Title,ReleaseYear,PublisherId,Price) values ('God of War',2018,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('God of War: Ragnarok',2022,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Red Dead Redemption',2010,1,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Red Dead Redemption 2',2018,1,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Death Stranding',2019,17,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Metal Gear Solid V: The Phantom Pain',2015,12,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Max Payne 3',2012,1,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Doom',2016,16,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Grand Theft Auto V',2013,1,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Life is Strange',2015,11,19.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Assassin''s Creed: Odyssey',2018,10,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Horizon Zero Dawn',2017,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Far Cry 4',2014,10,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Far Cry 5',2018,10,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Far Cry 6',2021,10,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Hitman: Absolution',2012,11,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Resident Evil VII: Biohazard',2017,14,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Spider-Man',2018,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Assassin''s Creed IV: Black Flag',2013,10,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Uncharted 4: A Thief''s End',2016,18,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Days Gone',2019,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Detroit: Become Human',2018,4,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Shadow of the Tomb Raider',2018,11,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('Forza Horizon 4',2018,5,59.99)
insert into Games(Title,ReleaseYear,PublisherId,Price) values ('The Witcher 3: Wild Hunt',2015,18,59.99)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('The Last of Us', 2013, 2, 60, 10)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('The Legend of Zelda: Breath of the Wild', 2017, 3, 80, 15)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Final Fantasy VII Remake', 2020, 4, 70, 20)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('BioShock Infinite', 2013, 5, 40, 25)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Super Mario Odyssey', 2017, 6, 50, 30)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Super Mario Galaxy 2', 2010, 6, 30, 35)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Minecraft', 2011, 7, 20, 40)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('The Elder Scrolls V: Skyrim', 2011, 8, 60, 45)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Super Smash Bros. Ultimate', 2018, 9, 70, 50)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Dark Souls III', 2016, 11, 50, 60)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Overwatch', 2016, 13, 60, 70)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Monster Hunter: World', 2018, 14, 40, 75)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Fallout 4', 2015, 15, 50, 80)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('The Legend of Zelda: Ocarina of Time', 1998, 3, 20, 85)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Portal 2', 2011, 16, 50, 90)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Mass Effect 2', 2010, 17, 40, 95)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Dragon Quest XI: Echoes of an Elusive Age', 2018, 18, 60, 100)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('FIFA 21', 2020, 18, 60, 10)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Call of Duty: Warzone', 2020, 12, 45, 15)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Among Us', 2018, 16, 5, 20)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Dota 2', 2013, 17, 10, 0)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Fortnite Battle Royale', 2017, 13, 35, 30)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Apex Legends', 2019, 14, 0, 35)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Animal Crossing: New Horizons', 2020, 6, 60, 45)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('The Last of Us Part II', 2020, 2, 70, 0)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Final Fantasy XIV', 2013, 4, 13, 55)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Monster Hunter World: Iceborne', 2019, 14, 40, 60)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Star Wars Jedi: Fallen Order', 2019, 10, 60, 65)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Sekiro: Shadows Die Twice', 2019, 11, 60, 70)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Resident Evil 2', 2019, 11, 60, 80)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Devil May Cry 5', 2019, 12, 60, 85)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('A Way Out', 2018, 16, 20, 90)
INSERT INTO Games (Title, ReleaseYear, PublisherId, Price, Discount) VALUES ('Hitman 2', 2018, 17, 60, 95)

update Games set Discount = 20 where Title = 'God of War'
update Games set Discount = 60 where Title = 'Red Dead Redemption'
update Games set Discount = 42 where Id=7
update Games set Discount = 15 where Id=8
update Games set Discount = 75 where Id=9
update Games set Discount = 18 where Id=10
update Games set Discount = 28 where Id=13
update Games set Discount = 62 where Id=16
update Games set Discount = 12 where Id=17
update Games set Discount = 25 where Id=19
update Games set Discount = 12 where Id=23
update Games set Discount = 8 where Id=25

insert into GamePlatforms values(1,3)
insert into GamePlatforms values(1,5)
insert into GamePlatforms values(2,3)
insert into GamePlatforms values(2,4)
insert into GamePlatforms values(3,2)
insert into GamePlatforms values(3,8)
insert into GamePlatforms values(4,3)
insert into GamePlatforms values(4,9)
insert into GamePlatforms values(4,5)
insert into GamePlatforms values(5,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(6,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(7,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(8,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(9,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(10,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(11,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(12,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(13,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(14,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(15,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(16,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(17,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(18,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(19,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(20,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(21,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(22,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(23,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(24,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(25,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(26,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(27,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(28,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(29,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(30,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(31,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(32,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(33,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(34,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(35,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(36,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(37,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(38,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(39,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(40,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(41,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(42,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(43,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(44,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(45,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(46,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(47,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(48,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(49,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(50,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(51,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(52,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(53,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(54,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(55,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(56,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(57,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GamePlatforms values(58,ABS(CHECKSUM(NEWID()) % 13) + 1)

insert into GameGenres values(1,1)
insert into GameGenres values(1,2)
insert into GameGenres values(2,1)
insert into GameGenres values(2,2)
insert into GameGenres values(3,1)
insert into GameGenres values(3,2)
insert into GameGenres values(3,16)
insert into GameGenres values(3,17)
insert into GameGenres values(3,18)
insert into GameGenres values(4,1)
insert into GameGenres values(4,2)
insert into GameGenres values(4,16)
insert into GameGenres values(4,17)
insert into GameGenres values(4,18)
insert into GameGenres values(5,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(6,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(7,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(8,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(9,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(10,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(11,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(12,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(13,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(14,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(15,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(16,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(17,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(18,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(19,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(20,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(21,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(22,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(23,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(24,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(25,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(26,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(27,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(28,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(29,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(30,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(31,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(32,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(33,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(34,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(35,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(36,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(37,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(38,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(39,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(40,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(41,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(42,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(43,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(44,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(45,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(46,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(47,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(48,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(49,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(50,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(51,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(52,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(53,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(54,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(55,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(56,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(57,ABS(CHECKSUM(NEWID()) % 13) + 1)
insert into GameGenres values(58,ABS(CHECKSUM(NEWID()) % 13) + 1)

delete from GameRegions where GameId = ABS(CHECKSUM(NEWID()) % 58) + 3 and RegionId = ABS(CHECKSUM(NEWID()) % 4) + 1


insert into Customers(Email,Username,[Password],RegionId,[Address])
values
('amaan@mail.com','Amaan Al Mir','202cb962ac59075b964b07152d234b70',ABS(CHECKSUM(NEWID()) % 4) + 1,null),
('raman@mail.com','Raman Raghav','250cf8b51c773f3f8dc8b4be867a9a02',ABS(CHECKSUM(NEWID()) % 4) + 1,'Mumbai, India'),
('johnwick@continental.com','Johnathan Wick','8ef9ae32e7b1351f139e074c18df9371',ABS(CHECKSUM(NEWID()) % 4) + 1,null),
('user123@gmail.com','User 123','6ad14ba9986e3615423dfca256d04e3f',ABS(CHECKSUM(NEWID()) % 4) + 1,null),
('wahid@yahoo.com','Wahid Uddin','ac6f3d4d696ba928a03f70cbbef83356',ABS(CHECKSUM(NEWID()) % 4) + 1,'Doha, Qatar'),
('shamsh@outlook.com','Umm Fateh Ali','323081f5b83f4340ab5a219fdb01e8da',ABS(CHECKSUM(NEWID()) % 4) + 1,'Jharkhand, India'),
('sania66@hotmail.com','Sabila Ahmed','e63aa50cb57c494b8b77d8d342e66624',ABS(CHECKSUM(NEWID()) % 4) + 1,'Alberta, Canada'),
('looneytunes@gmail.com','Looney Tunes','596a96cc7bf9108cd896f33c44aedc8a',ABS(CHECKSUM(NEWID()) % 4) + 1,'Ney York city, New york, United States');

update Customers set DefaultPaymentMethodId=2 where Username='Amaan Al Mir'
update Customers set DefaultPaymentMethodId=1 where Username='Sabila Ahmed'

insert into Reviews values(1,1,10,'This Game is amazing!')
insert into Reviews values(1,2,10,'I love this game!')
insert into Reviews values(ABS(CHECKSUM(NEWID()) % 8) + 1,ABS(CHECKSUM(NEWID()) % 58) + 1,ABS(CHECKSUM(NEWID()) % 10) + 1,NULL)

declare @id1 int = ABS(CHECKSUM(NEWID()) % 8) + 1
declare @id2 int = ABS(CHECKSUM(NEWID()) % 58) + 1
declare @id3 int = ABS(CHECKSUM(NEWID()) % 5) + 1
exec PurchaseGame @customerid=@id1,@gameid=@id2,@paymentmethod=@id3

select * from Customers
select * from PaymentMethods
select * from Transactions







